### ISSUE TITLE
Simple user

### ISSUE THREAD

**Issue by warlock39** [lunches-platform/api#54]
Just store and retrieve customer relative information. Without authentication.

Expose next new API endpoints:

**Get list of all registered users**:

```
GET /users HTTP/1.1
Content-Type: application/json
Host: api.lunches.com.ua
```

**Get user by username**:

```
GET /users/German%20Yerzhakov HTTP/1.1
Content-Type: application/json
Host: api.lunches.com.ua
```

**Get user by pattern, or which username contains specified chars**:

```
GET /users?like=yur HTTP/1.1
Content-Type: application/json
Host: api.lunches.com.ua
```

**Comment by dezoxel** [comment]
@warlock39 Please return HTTP 200 when no users found using endpoint `GET /users?like=yur`. It is ok to return when we try to fetch only one record. 404 for one entity means that we can't proceed in no way for displaying the item thus we forced to show error page. But when we try fetch the list of entities 404 code is not suitable since the empty list is a valid resource too.

In practice, I can't implement autocomplete since angular-material component is waiting from the the empty array if no results found

**Comment by warlock39** [comment]
@dezoxel , agree. It is a bug, 404 for collection filtering was not my intension

**Comment by warlock39** [comment]
@dezoxel , fixed
@Kostya47 , please test

**Comment by Kostya47** [comment]
Verified.
